[tool.poetry]
name = "infrahub-agent"
version = "0.1.0"
description = ""
authors = ["ubaumann <github@m.ubaumann.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
